import type { Metadata } from 'next';
import AppWrapper from '@/components/AppWrapper';
import { ReactNode } from 'react';
import Navbar from '@/components/Navbar';
import { CampaignProvider } from '@/hooks/useCampaign';
import { UserProvider } from '@/hooks/useUser';
import { AlertProvider } from '@/hooks/useAlert';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AlertProvider>
          <UserProvider>
            <CampaignProvider>
              <AppWrapper>
                <Navbar />
                {children}
              </AppWrapper>
            </CampaignProvider>
          </UserProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
