name: Deploy with Pulumi on Push to Prod

on:
  push:
    branches:
      - prod
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        working-directory: infra
        run: |
          venv/Scripts/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Pulumi
        working-directory: infra
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:/home/runner/.pulumi/bin
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Pulumi
        working-directory: infra
        run: pulumi up --yes
